name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checdkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
  deploy:

    runs-on: ubuntu-latest
    
    needs: tests

    steps:
    - uses: actions/checkout@v2

    - run: git remote add heroku https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/${{secrets.HEROKU_APP_NAME}}.git
    - run: git filter-branch -- --all
    - run: git push heroku HEAD:master -f
    
    ## - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
    ##  with:
    ##      heroku_api_key: ${{secrets.HEROKU_API_KEY}}
    ##      heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
    ##      buildpack: "https://github.com/jincod/dotnetcore-buildpack"
    
    

